#index:
#    path: /
#    controller: App\Controller\Default2Controller::index
api_auth_login:
  path: /api/auth/login
  methods:  [POST]

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

api:
  prefix: /api
  resource: '../src/Controller/Api'

